# Generated by Django 4.2.7 on 2024-01-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy', models.CharField(max_length=50)),
                ('sad', models.CharField(max_length=50)),
                ('angry', models.CharField(max_length=50)),
                ('neutral', models.CharField(max_length=50)),
            ],
        ),
    ]
