# Generated by Django 4.2.7 on 2024-01-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencedata',
            name='angry',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='preferencedata',
            name='happy',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='preferencedata',
            name='neutral',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='preferencedata',
            name='sad',
            field=models.JSONField(),
        ),
    ]
